version: 2.0
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: composer install
      - run: npm run build
      - run: npx grunt build